// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220605170949_mig_writer")]
    partial class mig_writer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Blog", b =>
                {
                    b.Property<int>("BlogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlogBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BlogDurum")
                        .HasColumnType("bit");

                    b.Property<string>("BlogImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BlogTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Blogicerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogkucukImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategorykategoriID")
                        .HasColumnType("int");

                    b.Property<int>("kategoriID")
                        .HasColumnType("int");

                    b.Property<int>("yazarID")
                        .HasColumnType("int");

                    b.HasKey("BlogID");

                    b.HasIndex("CategorykategoriID");

                    b.HasIndex("yazarID");

                    b.ToTable("blogs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Property<int>("kategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kategoriAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kategoricerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("kategoridurum")
                        .HasColumnType("bit");

                    b.HasKey("kategoriID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Yazar", b =>
                {
                    b.Property<int>("yazarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("yazarAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("yazarDurum")
                        .HasColumnType("bit");

                    b.Property<string>("yazarHakkinda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yazarImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yazarMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yazarSifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("yazarID");

                    b.ToTable("yazars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.hakkimda", b =>
                {
                    b.Property<int>("hakkimdaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("hakkimdaDetay1")
                        .HasColumnType("int");

                    b.Property<int>("hakkimdaDetay2")
                        .HasColumnType("int");

                    b.Property<int>("hakkimdaDurum")
                        .HasColumnType("int");

                    b.Property<int>("hakkimdaHaritaLokasyon")
                        .HasColumnType("int");

                    b.Property<int>("hakkimdaImg1")
                        .HasColumnType("int");

                    b.Property<int>("hakkimdaImg2")
                        .HasColumnType("int");

                    b.HasKey("hakkimdaID");

                    b.ToTable("hakkimdas");
                });

            modelBuilder.Entity("EntityLayer.Concrete.iletisim", b =>
                {
                    b.Property<int>("iletisimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("iletisimBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("iletisimDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("iletisimDurum")
                        .HasColumnType("bit");

                    b.Property<string>("iletisimKullaniciAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iletisimMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iletisimMesaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iletisimID");

                    b.ToTable("iletisims");
                });

            modelBuilder.Entity("EntityLayer.Concrete.yorumlar", b =>
                {
                    b.Property<int>("yorumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<string>("yorumAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yorumBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("yorumDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("yorumDurum")
                        .HasColumnType("bit");

                    b.Property<string>("yorumicerik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("yorumID");

                    b.HasIndex("BlogID");

                    b.ToTable("yorumlars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Blog", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategorykategoriID");

                    b.HasOne("EntityLayer.Concrete.Yazar", "yazar")
                        .WithMany("blogs")
                        .HasForeignKey("yazarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("yazar");
                });

            modelBuilder.Entity("EntityLayer.Concrete.yorumlar", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Blog", "Blog")
                        .WithMany("yorumlars")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Blog", b =>
                {
                    b.Navigation("yorumlars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Yazar", b =>
                {
                    b.Navigation("blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
